### ISSUE TITLE
Should the Docker image allow for setting database connection information directly?

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/django-email-relay#65]
Right now, the relay service Docker image -- using the code within `src/service/__init__.py` -- only allows for setting the database connection via a `DATABASE_URL`. This is how I prefer to do it with all of our Django applications. However, I wonder if other users may prefer to set the `HOST`, `PORT`, etc., directly.

Leaving this open for now to gather any feedback.

**Comment by jefftriplett** [comment]
What's the main concern? The URI spec allows for extra config to be passed though as query string options `...&option1=true&option2=false`. See https://github.com/jazzband/dj-database-url/blob/master/dj_database_url/__init__.py#L47

I adopted `DATABASE_URL` a decade+ ago because Heroku used it and now everyone supports it. So we could go more granular with individual settings, but I don't think we need to. 

If we did, this is the pattern I use in other projects (`environs[django]` friendly btw):

```python
try:
    DATABASES = {"default": env.db("DATABASE_URL")}
except ImproperlyConfigured:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "HOST": env("PGHOST"),
            "NAME": env("PGDATABASE"),
            "PASSWORD": env("PGPASSWORD"),
            "PORT": env.int("PGPORT", default=5432),
            "USER": env("PGUSER"),
            "CONN_MAX_AGE": 0,
            "OPTIONS": {"MAX_CONNS": 600},
        }
    }
```

**Comment by joshuadavidthomas** [comment]
No huge concern. I was just trying to fill out all the missing documentation and noticed that provided service Docker image only takes a `DATABASE_URL` and wasn't sure if there were people out there that would want the flexibility of setting all of the options directly. Just getting way ahead of myself thinking of potential future end users, but I wanted to raise it nonetheless.

**Comment by joshuadavidthomas** [comment]
Closing as not planned for now. Open to considering this in the future.
